<a href="https://colab.research.google.com/github/tanahiro1004/python_repository/blob/main/Numpy_nyumon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

## **多次元配列を定義**
ndarrayというクラスで多次元配列を表現

ndarrayオブジェクトは、shapeという属性を持っている。多次元配列の形が保存されている。

shapeは多次元配列の次元数を表す

ndimは階層(リストの深さ)を表す。

sizeは多次元配列の要素数を表す。

In [ ]:
a = np.array([[1,2,3], [4,5,6],[7,8,9]])

print(f"{a}\n  a.shape = {a.shape}\n  a.ndim = {a.ndim}\n  a.size = {a.size}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
  a.shape = (3, 3)
  a.ndim = 2
  a.size = 9


ndarrayの作成方法には、np.array()を用いてPythonのリストから多次元配列を作る方法以外にも存在する

In [ ]:
#要素が全て0で埋められたndarrayを作成
a = np.zeros((2,3))
print(f"a\n{a}\n")

#要素が全て1で埋められたndarrayを作成
b = np.ones((3,3))
print(f"b\n{b}\n")

#要素が指定した値で埋められたndarrayを作成
c = np.full((3,3),5)
print(f"c\n{c}\n")

#指定された大きさの単位行列を表すndarrayを作る
d = np.eye(5)
print(f"d\n{d}\n")

#指定した形で0~1の間の乱数で要素を埋めたndarrayを作成する
e = np.random.random((4,5))
print(f"e\n{e}\n")

#3から始まり10になるまで1ずつ増加する数列を作る（10は含まれない）
f = np.arange(3,10,1)
print(f"f\n{f}\n")

a
[[0. 0. 0.]
 [0. 0. 0.]]

b
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

c
[[5 5 5]
 [5 5 5]
 [5 5 5]]

d
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

e
[[0.09217077 0.46142389 0.61391671 0.47703116 0.43270363]
 [0.72271641 0.93248803 0.73987819 0.33400812 0.57283006]
 [0.32641509 0.59215976 0.04103353 0.2367413  0.94951736]
 [0.15936433 0.05812163 0.51315504 0.43375255 0.36675217]]

f
[3 4 5 6 7 8 9]



**既存のndarrayから要素を指定して新たなndarrayを作成**することも可能

**選択したい行と列を順にそれぞれリストとして与えること**でも行える

cの選択した３つの値は行と列を指している。初めのリストが0行目、2行目、1行目を選択している

次のリストは1列目、1列目、0列目を選択している。同一のインデックスの行の値と列の値に一致するaの値を取得する

In [ ]:
a = np.array([[1,2,3],[3,6,9],[4,8,12]])

b = np.array([a[0,1], a[1,1], a[2,2]])
print(f"b\n {b}")

#下の場合a[0,1]とa[2,1]とa[1,0]の値を取得してndarrayを作成する
c = a[[0,2,1],[1,1,0]]
print(f"c\n {c}")

b
 [ 2  6 12]
c
 [2 8 3]


In [ ]:
center = e[1:3,1:4]
center

print("Shape of e:", e.shape)
print("Shape of center",center.shape)

Shape of e: (4, 5)
Shape of center (2, 3)


上記のようにスライス表記を用いて**選択したい要素を範囲指定することができる**

また、スライスを用いて取り出したndarrayの一部に対し、値を代入することもできる

In [ ]:
e[1:3,1:4] = 0
e

array([[0.09217077, 0.46142389, 0.61391671, 0.47703116, 0.43270363],
       [0.72271641, 0.        , 0.        , 0.        , 0.57283006],
       [0.32641509, 0.        , 0.        , 0.        , 0.94951736],
       [0.15936433, 0.05812163, 0.51315504, 0.43375255, 0.36675217]])

Pythonのint型はNumpyのint64型になる

float型も同様でNumpyのfloat64型になる

これはPythonのint型はNumpyのint_型に対応づけれており、場合によってはint64型、int32型となる。

これはfloat型も同様である

特定の方を指定し、ndarrayを作成するには以下のようにする

In [ ]:
x = np.array([1,2,3], dtype=np.float32)

#以下のように文字列での指定も行える
# x = np.array([1,2,3],dtype = "float32")
# x = np.array([1,2,3],dtype = "f")

x.dtype

dtype('float32')

一度あるデータ型で定義した配列のデータ型を別のものに変更するには、**astype**を用いて変換する。

In [ ]:
x = x.astype(np.float64)

x.dtype

dtype('float64')

同じ形の行列を２つ定義すると、要素ごとの加減乗除を行える

Numpyでは、与えられた多次元配列に対して要素ごとに計算を行う関数が色々と用意されている。

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

#要素ごとに平方根を計算する
b = np.sqrt(a)
print(f"b\n {b} ")

#要素ごとに値をn乗する
n = 2
c = np.power(a,n)
#n乗は以下のようしても大丈夫
# c = a ** n
print(f"c\n {c}")

b
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]] 
c
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]



bの１行3列の各値が同列のaの３行3列の値に足されている。

aの2行3列の値はbの3列の値が加算される。

In [ ]:
b = np.array([1,2,3])
c = a + b
c

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

上記の計算が実行できるのはNumpyがbの1行3列の形をaと同じ形に暗黙的に揃えているからである。

この操作を**ブロードキャスト**という

Numpyは自動的に小さい方の配列をブロードキャストし大きい配列の形と合わせる。

ブロードキャストによって計算が可能になるためにはルールがある

### 「２つの配列の各次元が同じ大きさになっているか、どちらかが１であること」

In [ ]:
a = np.random.randint(0,10,(2,1,3))
b = np.random.randint(0,10,(3,1))

print("a:\n",a)
print("b:\n",b)

c = a + b
print("c:\n",c)
print(c.shape)


a:
 [[[2 9 3]]

 [[5 7 4]]]
b:
 [[6]
 [6]
 [8]]
c:
 [[[ 8 15  9]
  [ 8 15  9]
  [10 17 11]]

 [[11 13 10]
  [11 13 10]
  [13 15 12]]]
(2, 3, 3)


上のコードの場合、２つの配列の末尾の次元数が3と1である。これは、条件のどちらかが1であることを満たしている。

aは３次元であるが、bは２次元である。この場合、bは一番上の次元にサイズが1の次元が追加された形として扱われる。(1,3,1)

２つの配列の各次元ごとのサイズの最大値をとった形(2,3,3)にブロードキャストされる


In [ ]:
print("Original shape", b.shape)
print(b)
b_expanded = b[np.newaxis, : , : ]
print("Added new axis to the top:", b_expanded.shape)
print(b_expanded)

Original shape (3, 1)
[[6]
 [6]
 [8]]
Added new axis to the top: (1, 3, 1)
[[[6]
  [6]
  [8]]]


np.newaxisが指定された位置に新しい次元が挿入される。配列が持つ数値の数は変わっていない

%%timeitというJupyter Notebookで使用できるセル。実行時間を計測するセル

In [4]:
a = np.random.randint(0,10,(5,5))

b = np.array([1,2,3,4,5])

c = np.empty([5,5])


In [5]:
%%timeit
for i in range(a.shape[0]):
  c[i, :] = a[i, :] +b

The slowest run took 10.94 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 8.01 µs per loop


上記のようにfor文を使うのではなく、ブロードキャストを利用した計算なら実行速度は数倍早くなる

In [6]:
%%timeit
c = a + b

The slowest run took 41.69 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.19 µs per loop


行列同士の積の計算は * ではなくnp.dot()関数を用いる。

In [10]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(0,10,(3,3))
print(a,b)

C = np.dot(a,b)
print(C)

[[4 6 4]
 [8 1 4]
 [5 0 2]] [[8 9 8]
 [8 7 8]
 [7 5 1]]
[[108  98  84]
 [100  99  76]
 [ 54  55  42]]


a.dot(b)という記述方法もある

In [13]:
x = np.random.randint(0,10,(8,10))

#平均値
avg = x.mean()

#分散
var = x.var()

#標準偏差
std = x.std()

#最大値
max = x.max()

#最小値
min = x.min()

print(x)
print(f"平均値：{avg},  分散：{var},  標準偏差：{std}")
print(f"最大値：{max}, 最小値：{min}")

[[3 5 9 3 1 7 5 4 7 4]
 [5 0 2 4 3 9 2 9 4 7]
 [6 2 9 2 5 6 7 8 2 4]
 [6 7 2 5 0 0 3 5 5 1]
 [7 3 2 4 8 6 7 1 7 4]
 [3 9 7 9 7 2 9 3 1 9]
 [6 0 2 3 4 9 2 7 9 9]
 [8 3 4 1 6 0 5 5 2 0]]
平均値：4.6375,  分散：7.706093749999999,  標準偏差：2.7759851854792017
最大値：9, 最小値：0


特定の次元の平均（平均以外も出せる）を出せる

In [17]:
x.mean(axis = 1)

array([4.8, 4.5, 5.1, 3.4, 4.9, 5.9, 5.1, 3.4])